-- Migration 005: Add real Monster Manual images from 5etools-img GitHub mirror
-- Source: https://github.com/5etools-mirror-2/5etools-img (public, CORS-friendly)

UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Kobold.webp'            WHERE name = 'Кобольд'                AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Bandit.webp'            WHERE name = 'Бандит'                 AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Guard.webp'             WHERE name = 'Стражник'               AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Zombie.webp'            WHERE name = 'Зомби чумы'             AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Crawling%20Claw.webp'   WHERE name = 'Жуткий коготь'         AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Troll.webp'             WHERE name = 'Тролль'                 AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Hobgoblin.webp'         WHERE name = 'Хоббгоблин'             AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Ghoul.webp'             WHERE name = 'Гуль'                   AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Wyvern.webp'            WHERE name = 'Виверна'                AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Brown%20Bear.webp'      WHERE name = 'Медведь бурый'          AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Giant%20Spider.webp'    WHERE name = 'Гигантский паук'        AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Mummy.webp'             WHERE name = 'Мумия'                  AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Chimera.webp'           WHERE name = 'Химера'                 AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Medusa.webp'            WHERE name = 'Медуза'                 AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Cyclops.webp'           WHERE name = 'Циклоп'                 AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Fire%20Elemental.webp'  WHERE name = 'Огненный элементаль'    AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Air%20Elemental.webp'   WHERE name = 'Воздушный элементаль'   AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Vampire.webp'           WHERE name = 'Вампир'                 AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Young%20Red%20Dragon.webp'  WHERE name = 'Дракон молодой красный' AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Lich.webp'              WHERE name = 'Личь'                   AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Giant%20Eagle.webp'     WHERE name = 'Гигантский орёл'        AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Manticore.webp'         WHERE name = 'Мантикора'              AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Hill%20Giant.webp'      WHERE name = 'Великан холмов'         AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Young%20Blue%20Dragon.webp' WHERE name = 'Дракон молодой синий'  AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Ghost.webp'             WHERE name = 'Призрак'                AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Mind%20Flayer.webp'     WHERE name = 'Ум-пожиратель'          AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Roc.webp'               WHERE name = 'Рух'                    AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Horned%20Devil.webp'    WHERE name = 'Дьявол рогатый'         AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Balor.webp'             WHERE name = 'Балор'                  AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Tarrasque.webp'         WHERE name = 'Тарраск'                AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Goblin.webp'            WHERE name = 'Гоблин'                 AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Skeleton.webp'          WHERE name = 'Скелет'                 AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Ogre.webp'              WHERE name = 'Огр'                    AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Wolf.webp'              WHERE name = 'Волк'                   AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Dire%20Wolf.webp'       WHERE name = 'Лютый волк'             AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Werewolf.webp'          WHERE name = 'Оборотень'              AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Wight.webp'             WHERE name = 'Вурдалак'               AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Ghast.webp'             WHERE name = 'Упырь'                  AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Centaur.webp'           WHERE name = 'Кентавр'                AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Harpy.webp'             WHERE name = 'Гарпия'                 AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Minotaur.webp'          WHERE name = 'Минотавр'               AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Griffon.webp'           WHERE name = 'Грифон'                 AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Beholder.webp'          WHERE name = 'Наблюдатель'            AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Beholder.webp'          WHERE name = 'Бехолдер'               AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Aboleth.webp'           WHERE name = 'Аболет'                 AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Specter.webp'           WHERE name = 'Спектр'                 AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Banshee.webp'           WHERE name = 'Баньши'                 AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Wraith.webp'            WHERE name = 'Призрак-тень'           AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Shadow.webp'            WHERE name = 'Тень'                   AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Imp.webp'               WHERE name = 'Бес'                    AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Succubus.webp'          WHERE name = 'Суккуб'                 AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Succubus.webp'          WHERE name = 'Инкуб'                  AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Pit%20Fiend.webp'       WHERE name = 'Дьявол ямы'             AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Marilith.webp'          WHERE name = 'Марилит'                AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Water%20Elemental.webp' WHERE name = 'Водный элементаль'      AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Earth%20Elemental.webp' WHERE name = 'Земляной элементаль'    AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Young%20Green%20Dragon.webp' WHERE name = 'Дракон молодой зелёный' AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Young%20Black%20Dragon.webp' WHERE name = 'Дракон молодой чёрный'  AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Young%20White%20Dragon.webp' WHERE name = 'Дракон молодой белый'   AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Flameskull.webp'        WHERE name = 'Огненный череп'         AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Revenant.webp'          WHERE name = 'Ревенант'               AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Mummy%20Lord.webp'      WHERE name = 'Повелитель мумий'       AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Vampire%20Spawn.webp'   WHERE name = 'Вампирский потомок'     AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Swarm%20of%20Rats.webp' WHERE name = 'Рой крыс'               AND is_homebrew = false;
UPDATE bestiary SET image_url = 'https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/MM/Rat.webp'               WHERE name = 'Крыса'                  AND is_homebrew = false;
